version: "3.7"

services:
    web_dev:
        image: web_dev
        container_name: web_dev
        build: 
            context: .
            dockerfile: dockerfile
        volumes:
          - "C:/Users/Harold/Documents/Docker/web_go/go:/root/go"
        ports:
            - "8080:8080"
            - "2222:22"
        privileged: true
        command: bash -c "/usr/sbin/init"

    postgres:
        image: postgres:17.3-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"
        

#     mongodb:
#         image: mongo
#         container_name: mongodb
#         environment:
#             MONGO_INITDB_ROOT_USERNAME: root
#             MONGO_INITDB_ROOT_PASSWORD: password
#             MONGO_INITDB_DATABASE: test
#         volumes:
#             - "C:/Users/Harold/Documents/Docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro"
#             - "C:/Users/Harold/Documents/Docker/mongo/volumn:/data/db"
#         ports:
#             - "27017:27017"
#         networks:
#             mongo-net:
#                 ipv4_address: 172.23.0.3

#     redis:
#         image: redis
#         container_name: redis
#         command: redis-server --requirepass password
#         volumes:
#             - "C:/Users/Harold/Documents/Docker/redis:/var/lib/redis/data"
#         ports:
#             - "6379"
#         networks:
#             mongo-net:
#                 ipv4_address: 172.23.0.4

# networks:
#     app_net:
#         external: true
#     mongo-net:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 172.23.0.0/16
#                   gateway: 172.23.0.1